services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    environment:
      TZ: 'America/Mexico_City'
      WEBPASSWORD: 'pi_password'
    volumes:
      - '/home/username/pihole/etc-pihole:/etc/pihole'
      - '/home/username/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
